# Generated by Django 4.1.2 on 2022-10-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
