# Generated by Django 4.1.2 on 2022-10-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_following_alter_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
