# Generated by Django 4.1.2 on 2022-10-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_user_followers_remove_user_following_follow_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='one_follow',
        ),
    ]
