# Generated by Django 4.1.4 on 2023-04-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_alter_post_like_users_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
