# Generated by Django 4.1.4 on 2023-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
