# Generated by Django 4.1.4 on 2023-04-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_user_bio_user_location_user_name_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
